[options]
library = "XApp"
version = "1.0"
target_path = "."
min_cfg_version = "2.2.15"
work_mode = "sys"
girs_directories = ["../../gir-files/"]

external_libraries = [
	"Cairo",
	"Gio",
	"GLib",
	"GObject",
	"Gtk",
]
